grails-app/domain/it/addressbook/Contact.groovy
package it.addressbook

class Contact {

    Date dateCreated
    Date lastUpdated

    String givenName
    String familyName
    String homeAddress

    //TODO validate every email
    static hasMany = [phoneList: Phone, emailList: Email]

    static constraints = {
        givenName size: 1..128
        familyName size: 1..128
        homeAddress nullable: true, size: 0..1024
        emailList nullable: false, minSize: 1
        phoneList nullable: true, minSize: 1
    }
}

grails-app/controllers/it/addressbook/ContactController.groovy
package it.addressbook



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ContactController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max, String familyName) {
        params.max = Math.min(max ?: 10, 100)
        def contactList = familyName ? Contact.findAllByFamilyNameIlike("%${familyName}%", params) : Contact.list(params)
        respond contactList, model:[contactInstanceCount: contactList.size()]
    }

    def show(Contact contactInstance) {
        respond contactInstance
    }

    def create() {
        respond new Contact(params)
    }

    @Transactional
    def save(Contact contactInstance) {
        if (contactInstance == null) {
            notFound()
            return
        }

        if (contactInstance.hasErrors()) {
            respond contactInstance.errors, view:'create'
            return
        }

        contactInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'contact.label', default: 'Contact'), contactInstance.id])
                redirect contactInstance
            }
            '*' { respond contactInstance, [status: CREATED] }
        }
    }

    def edit(Contact contactInstance) {
        respond contactInstance
    }

    @Transactional
    def update(Contact contactInstance) {
        if (contactInstance == null) {
            notFound()
            return
        }

        if (contactInstance.hasErrors()) {
            respond contactInstance.errors, view:'edit'
            return
        }

        contactInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Contact.label', default: 'Contact'), contactInstance.id])
                redirect contactInstance
            }
            '*'{ respond contactInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Contact contactInstance) {

        if (contactInstance == null) {
            notFound()
            return
        }

        contactInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Contact.label', default: 'Contact'), contactInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'contact.label', default: 'Contact'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def search(String familyName){
        def contactList = Contact.findByFamilyName(familyName)

    }
}

grails-app/views/contact/_form.gsp
<%@ page import="it.addressbook.Contact" %>



<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'givenName', 'error')} required">
	<label for="givenName">
		<g:message code="contact.givenName.label" default="Given Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="givenName" maxlength="128" required="" value="${contactInstance?.givenName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'familyName', 'error')} required">
	<label for="familyName">
		<g:message code="contact.familyName.label" default="Family Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="familyName" maxlength="128" required="" value="${contactInstance?.familyName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'homeAddress', 'error')} ">
	<label for="homeAddress">
		<g:message code="contact.homeAddress.label" default="Home Address" />
		
	</label>
	<g:textArea name="homeAddress" cols="40" rows="5" maxlength="1024" value="${contactInstance?.homeAddress}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'emailList', 'error')} required">
	<label for="emailList">
		<g:message code="contact.emailList.label" default="Email List" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="emailList" from="${it.addressbook.Email.list()}" multiple="multiple" optionKey="id" size="5" required="" value="${contactInstance?.emailList*.id}" class="many-to-many"/>
	<g:link controller="email" action="create">Add email address</g:link>
</div>

<div class="fieldcontain ${hasErrors(bean: contactInstance, field: 'phoneList', 'error')} ">
	<label for="phoneList">
		<g:message code="contact.phoneList.label" default="Phone List" />
		
	</label>
	<g:select name="phoneList" from="${it.addressbook.Phone.list()}" multiple="multiple" optionKey="id" size="5" value="${contactInstance?.phoneList*.id}" class="many-to-many"/>
	<g:link controller="phone" action="create">Add phone number</g:link>
</div>

grails-app/views/contact/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'contact.label', default: 'Contact')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-contact" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${contactInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${contactInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:contactInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/contact/edit.gsp
<%@ page import="it.addressbook.Contact" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'contact.label', default: 'Contact')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-contact" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${contactInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${contactInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:contactInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${contactInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/contact/index.gsp
<%@ page import="it.addressbook.Contact" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'contact.label', default: 'Contact')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
				<li style="float: right;">
					<g:form action="index">
						<button type="submit">
							<g:img dir="images" file="search.png" style="width: 20px;height: 20px; vertical-align: middle; margin-right: 2px;"></g:img>
						</button>
						<g:textField name="familyName" class=""/>
					</g:form>
				</li>
			</ul>
		</div>
		<div id="list-contact" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="givenName" title="${message(code: 'contact.givenName.label', default: 'Given Name')}" />
					
						<g:sortableColumn property="familyName" title="${message(code: 'contact.familyName.label', default: 'Family Name')}" />
					
						<g:sortableColumn property="homeAddress" title="${message(code: 'contact.homeAddress.label', default: 'Home Address')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'contact.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'contact.lastUpdated.label', default: 'Last Updated')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${contactInstanceList}" status="i" var="contactInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${contactInstance.id}">${fieldValue(bean: contactInstance, field: "givenName")}</g:link></td>
					
						<td>${fieldValue(bean: contactInstance, field: "familyName")}</td>
					
						<td>${fieldValue(bean: contactInstance, field: "homeAddress")}</td>
					
						<td><g:formatDate date="${contactInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${contactInstance.lastUpdated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${contactInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/contact/show.gsp
<%@ page import="it.addressbook.Contact" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'contact.label', default: 'Contact')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-contact" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-contact" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list contact">
			
				<g:if test="${contactInstance?.givenName}">
				<li class="fieldcontain">
					<span id="givenName-label" class="property-label"><g:message code="contact.givenName.label" default="Given Name" /></span>
					
						<span class="property-value" aria-labelledby="givenName-label"><g:fieldValue bean="${contactInstance}" field="givenName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.familyName}">
				<li class="fieldcontain">
					<span id="familyName-label" class="property-label"><g:message code="contact.familyName.label" default="Family Name" /></span>
					
						<span class="property-value" aria-labelledby="familyName-label"><g:fieldValue bean="${contactInstance}" field="familyName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.homeAddress}">
				<li class="fieldcontain">
					<span id="homeAddress-label" class="property-label"><g:message code="contact.homeAddress.label" default="Home Address" /></span>
					
						<span class="property-value" aria-labelledby="homeAddress-label"><g:fieldValue bean="${contactInstance}" field="homeAddress"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.emailList}">
				<li class="fieldcontain">
					<span id="emailList-label" class="property-label"><g:message code="contact.emailList.label" default="Email List" /></span>
					
						<g:each in="${contactInstance.emailList}" var="e">
						<span class="property-value" aria-labelledby="emailList-label"><g:link controller="email" action="show" id="${e.id}">${e?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.phoneList}">
				<li class="fieldcontain">
					<span id="phoneList-label" class="property-label"><g:message code="contact.phoneList.label" default="Phone List" /></span>
					
						<g:each in="${contactInstance.phoneList}" var="p">
						<span class="property-value" aria-labelledby="phoneList-label"><g:link controller="phone" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="contact.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${contactInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${contactInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="contact.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${contactInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:contactInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${contactInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>